# -*- python -*-
import os

Import('env')
env = env.Clone()
src_map = {
    'hello' : ['hello.cpp'],
    # 'ls1' : ['ls1.cpp'],
    # 'getcputc' : ['getcputc.cpp'],
    # 'mycat' : ['mycat.cpp'],
    # 'testerror' : ['testerror.cpp'],
    # 'uidgid' : ['uidgid.cpp'],
    # 'shell1' : ['shell1.cpp'],
    # 'shell2' : ['shell2.cpp']
}
libs = ['apue']

for k in src_map:
    env.Program(k, src_map[k], LIBS = libs)
