# -*- mode:python -*-
import sys
import os

Import('env')
env = env.Clone()

sub_dir = ['intro']

env.Lint(Glob('*/*.h'))

builds = env.SConscript(
    dirs=sub_dir,
    exports='env',
    duplicate=1)

